spring.application.name=flashline

server.port=9002

spring.datasource.url=jdbc:postgresql://localhost:5435/flashlinedb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true

# --- JWT ---
# 86400000 - 24h, 3600000 - 1h
#flashline.jwt.expiration-millis=86400000
flashline.jwt.expiration-millis=3600000